---
title: "Slalom Data Processing"
author: "C. Savonen, CCDL for ALSF"
date: "12/10/2018"
output: html_document
---
```{r Install Packages}
# Install Slalom if its not 
if (!("slalom" %in% installed.packages())) {
  source("https://bioconductor.org/biocLite.R")
  biocLite("slalom", suppressUpdates = FALSE)
}
# Attach the library
library("slalom")
```

```{r Import Data}
tx.counts <- readRDS(file.path("anoop_data", "patel.counts.data.RDS"))
```

```{r Format Data}
exprs_matrix <- SingleCellExperiment::logcounts(tx.counts)
tx.counts <- SingleCellExperiment::SingleCellExperiment(
    assays = list(logcounts = exprs_matrix)
)
gmtfile <- system.file("extdata", "reactome_subset.gmt", package = "slalom")
genesets <- GSEABase::getGmt(gmtfile)

model <- newSlalomModel(tx.counts, genesets, n_hidden = 5, min_genes = 10)

model <- initSlalom(model)

model <- trainSlalom(model, nIterations = 10)

rdsfile <- system.file("extdata", "sim_N_20_v3.rds", package = "slalom")
sim <- readRDS(rdsfile)
sce <- SingleCellExperiment::SingleCellExperiment(
    assays = list(logcounts = sim[["init"]][["Y"]])
)

gmtfile <- system.file("extdata", "reactome_subset.gmt", package = "slalom")
genesets <- GSEABase::getGmt(gmtfile)

genesets <- GSEABase::GeneSetCollection(
    lapply(genesets, function(x) {
        GSEABase::setName(x) <- gsub("REACTOME_", "", GSEABase::setName(x))
        GSEABase::setName(x) <- strtrim(GSEABase::setName(x), 30)
        x
    })
)
rownames(sce) <- unique(unlist(GSEABase::geneIds(genesets[1:20])))[1:500]
colnames(sce) <- 1:ncol(sce)

m <- newSlalomModel(sce, genesets[1:23], n_hidden = 1, min_genes = 1)

m <- initSlalom(m, pi_prior = sim[["init"]][["Pi"]], n_hidden = 1, seed = 222)

mm <- trainSlalom(m, minIterations = 400, nIterations = 5000, shuffle = TRUE,
                  pretrain = TRUE, seed = 222)

topTerms(m)

plotRelevance(m)

plotTerms(m)

plotLoadings(m, "CELL_CYCLE")

sce <- addResultsToSingleCellExperiment(sce, m)
```

```{r Save Data}

```